### ISSUE TITLE
wordpress xml 형식으로 댓글 export하기

### ISSUE THREAD

**Issue by benelog** [benelog/egloos-migration#21]
## raw data 처리
데이터 예시

- http://api.egloos.com/benelog/post/3120317/comment.xml
- http://api.egloos.com/benelog/post/3120317/comment.json

### 로직
- 이미지 처리
    - http://md.egloos.com/img/eg/profile_anonymous.jpg 일 때는 이미지 쓰지 않기
    - http://profile.egloos.net/d0032573_50.jpg 은 blog.benelog.net으로 바꾸기
- 저자 URL : writer_url보다는 homepage_url을 우선시하기

## export 스펙 참조
- https://import.disqus.com/test-benelog/
- https://help.disqus.com/developer/custom-xml-import-format
- https://help.disqus.com/troubleshooting/troubleshooting-imports

**Comment by benelog** [comment]
## TODO
- [x] 테스트용 import 파일 import 성공해보기
- [x] output 모델용 domain 클래스 정의
- [x] StaxEventItemWriter 만들기
- [x] 확장자가 없는  URL과  `*.html` 으로 들어갔을 때  동일한 처리
- [x] thread의 content는 넣어줄 필요가 있는지 확인
- [x] Processor 만들기

**Comment by benelog** [comment]
guest comment 옵션을 필수가 아니다.

**Comment by benelog** [comment]
format
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:dsq="http://www.disqus.com/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:wp="http://wordpress.org/export/1.0/"
>
  <channel>
    <item>
      <!-- title of article -->
      <title>정아빠의 하루</title>
      <!-- absolute URI to article -->
      <link>https://blog2.benelog.net/test.html</link>

      <content:encoded><![CDATA[행복해져요]]></content:encoded>

      <dsq:thread_identifier>test.html</dsq:thread_identifier>
      <wp:post_date_gmt>2010-09-20 09:13:44</wp:post_date_gmt>
      <!-- open/closed values are acceptable -->
      <wp:comment_status>open</wp:comment_status>
      <wp:comment>
        <!-- internal id of comment -->
        <wp:comment_id>21</wp:comment_id>
        <!-- author display name -->
        <wp:comment_author>나몰라</wp:comment_author>
        <!-- author email address -->
        <wp:comment_author_email>benelog@gmail.com</wp:comment_author_email>
        <!-- author url, optional -->
        <wp:comment_author_url>https://benelog.net/</wp:comment_author_url>
        <!-- author ip address -->
        <wp:comment_author_IP></wp:comment_author_IP>
        <wp:comment_date_gmt>2017-09-20 13:19:10</wp:comment_date_gmt>
        <wp:comment_content><![CDATA[판단하지 말자]]></wp:comment_content>
        <!-- is this comment approved? 0/1 -->
        <wp:comment_approved>1</wp:comment_approved>
        <!-- parent id (match up with wp:comment_id) -->
        <wp:comment_parent>0</wp:comment_parent>
      </wp:comment>
 
      <wp:comment>
        <!-- internal id of comment -->
        <wp:comment_id>22</wp:comment_id>
        <!-- author display name -->
        <wp:comment_author>나몰라</wp:comment_author>
        <!-- author email address -->
        <wp:comment_author_email>benelog@gmail.com</wp:comment_author_email>
        <!-- author url, optional -->
        <wp:comment_author_url>https://benelog.net/</wp:comment_author_url>
        <!-- author ip address -->
        <wp:comment_author_IP></wp:comment_author_IP>
        <wp:comment_date_gmt>2017-09-20 13:19:10</wp:comment_date_gmt>
        <wp:comment_content><![CDATA[어떻게]]></wp:comment_content>
        <!-- is this comment approved? 0/1 -->
        <wp:comment_approved>1</wp:comment_approved>
        <!-- parent id (match up with wp:comment_id) -->
        <wp:comment_parent>21</wp:comment_parent>
      </wp:comment>

      <wp:comment>
        <!-- internal id of comment -->
        <wp:comment_id>23</wp:comment_id>
        <!-- author display name -->
        <wp:comment_author>나몰라</wp:comment_author>
        <!-- author email address -->
        <wp:comment_author_email>benelog@gmail.com</wp:comment_author_email>
        <!-- author url, optional -->
        <wp:comment_author_url>https://benelog.net/</wp:comment_author_url>
        <!-- author ip address -->
        <wp:comment_author_IP></wp:comment_author_IP>
        <wp:comment_date_gmt>2017-09-20 13:19:10</wp:comment_date_gmt>
        <wp:comment_content><![CDATA[이런걸 어떠나]]></wp:comment_content>
        <!-- is this comment approved? 0/1 -->
        <wp:comment_approved>1</wp:comment_approved>
        <!-- parent id (match up with wp:comment_id) -->
        <wp:comment_parent>0</wp:comment_parent>
      </wp:comment>
    </item>
  </channel>
</rss>

```

**Comment by benelog** [comment]
https://dev-benelog-1.disqus.com/admin/settings/advanced/

**Comment by benelog** [comment]
https://github.com/benelog/egloos-migration/commit/f58cc7b7f820d1037d52eecc1157e3039e9b120e
